// Friendship Game Questions Database
const questionsDatabase = {
    en: [
        "Who is most likely to become famous?",
        "Who would survive the longest in a zombie apocalypse?",
        "Who is most likely to forget their own birthday?",
        "Who would be the best at keeping a secret?",
        "Who is most likely to become a millionaire?",
        "Who would be the first to get married?",
        "Who is most likely to move to another country?",
        "Who would be the best travel companion?",
        "Who is most likely to become a teacher?",
        "Who would win in a dance battle?",
        "Who is most likely to adopt a stray animal?",
        "Who would be the best at solving puzzles?",
        "Who is most likely to become a chef?",
        "Who would be the funniest stand-up comedian?",
        "Who is most likely to learn a new language fluently?",
        "Who would be the best at giving advice?",
        "Who is most likely to become an artist?",
        "Who would be the most adventurous eater?",
        "Who is most likely to write a book?",
        "Who would be the best at organizing events?",
        "Who is most likely to become a doctor?",
        "Who would be the most likely to go skydiving?",
        "Who is most likely to become a social media influencer?",
        "Who would be the best at remembering birthdays?",
        "Who is most likely to become a professional athlete?",
        "Who would be the most likely to cry during a movie?",
        "Who is most likely to become an entrepreneur?",
        "Who would be the best at telling jokes?",
        "Who is most likely to become a musician?",
        "Who would be the most likely to get lost?",
        "Who is most likely to become a politician?",
        "Who would be the best at karaoke?",
        "Who is most likely to become a scientist?",
        "Who would be the most likely to help a stranger?",
        "Who is most likely to become a photographer?",
        "Who would be the most likely to stay up all night?",
        "Who is most likely to become a lawyer?",
        "Who would be the best at making people laugh?",
        "Who is most likely to become a pilot?",
        "Who would be the most likely to win a game show?",
        "Who is most likely to become an actor?",
        "Who would be the best at keeping plants alive?",
        "Who is most likely to become a veterinarian?",
        "Who would be the most likely to forget where they parked?",
        "Who is most likely to become a fashion designer?",
        "Who would be the best at public speaking?",
        "Who is most likely to become a psychologist?",
        "Who would be the most likely to sing in the shower?",
        "Who is most likely to become a journalist?",
        "Who would be the best at giving hugs?",
        "Who is most likely to become an engineer?",
        "Who would be the most likely to talk to themselves?",
        "Who is most likely to become a nurse?",
        "Who would be the best at making friends?",
        "Who is most likely to become a coach?",
        "Who would be the most likely to collect something unusual?",
        "Who is most likely to become a librarian?",
        "Who would be the best at solving conflicts?",
        "Who is most likely to become a firefighter?",
        "Who would be the most likely to have the messiest room?"
    ],
    
    ar: [
        "من الأكثر احتمالاً أن يصبح مشهوراً؟",
        "من سيبقى على قيد الحياة أطول فترة في نهاية العالم؟",
        "من الأكثر احتمالاً أن ينسى عيد ميلاده؟",
        "من سيكون الأفضل في حفظ الأسرار؟",
        "من الأكثر احتمالاً أن يصبح مليونيراً؟",
        "من سيكون أول من يتزوج؟",
        "من الأكثر احتمالاً أن ينتقل إلى بلد آخر؟",
        "من سيكون أفضل رفيق سفر؟",
        "من الأكثر احتمالاً أن يصبح معلماً؟",
        "من سيفوز في معركة رقص؟",
        "من الأكثر احتمالاً أن يتبنى حيواناً ضالاً؟",
        "من سيكون الأفضل في حل الألغاز؟",
        "من الأكثر احتمالاً أن يصبح طاهياً؟",
        "من سيكون أطرف كوميديان؟",
        "من الأكثر احتمالاً أن يتعلم لغة جديدة بطلاقة؟",
        "من سيكون الأفضل في تقديم النصائح؟",
        "من الأكثر احتمالاً أن يصبح فناناً؟",
        "من سيكون الأكثر مغامرة في الطعام؟",
        "من الأكثر احتمالاً أن يكتب كتاباً؟",
        "من سيكون الأفضل في تنظيم الفعاليات؟",
        "من الأكثر احتمالاً أن يصبح طبيباً؟",
        "من الأكثر احتمالاً أن يقفز بالمظلة؟",
        "من الأكثر احتمالاً أن يصبح مؤثراً على وسائل التواصل؟",
        "من سيكون الأفضل في تذكر أعياد الميلاد؟",
        "من الأكثر احتمالاً أن يصبح رياضياً محترفاً؟",
        "من الأكثر احتمالاً أن يبكي أثناء مشاهدة فيلم؟",
        "من الأكثر احتمالاً أن يصبح رجل أعمال؟",
        "من سيكون الأفضل في إلقاء النكات؟",
        "من الأكثر احتمالاً أن يصبح موسيقياً؟",
        "من الأكثر احتمالاً أن يضيع؟",
        "من الأكثر احتمالاً أن يصبح سياسياً؟",
        "من سيكون الأفضل في الكاريوكي؟",
        "من الأكثر احتمالاً أن يصبح عالماً؟",
        "من الأكثر احتمالاً أن يساعد غريباً؟",
        "من الأكثر احتمالاً أن يصبح مصوراً؟",
        "من الأكثر احتمالاً أن يسهر طوال الليل؟",
        "من الأكثر احتمالاً أن يصبح محامياً؟",
        "من سيكون الأفضل في إضحاك الناس؟",
        "من الأكثر احتمالاً أن يصبح طياراً؟",
        "من الأكثر احتمالاً أن يفوز في برنامج مسابقات؟",
        "من الأكثر احتمالاً أن يصبح ممثلاً؟",
        "من سيكون الأفضل في الحفاظ على النباتات حية؟",
        "من الأكثر احتمالاً أن يصبح طبيباً بيطرياً؟",
        "من الأكثر احتمالاً أن ينسى مكان ركن سيارته؟",
        "من الأكثر احتمالاً أن يصبح مصمم أزياء؟",
        "من سيكون الأفضل في الخطابة؟",
        "من الأكثر احتمالاً أن يصبح طبيباً نفسياً؟",
        "من الأكثر احتمالاً أن يغني في الحمام؟",
        "من الأكثر احتمالاً أن يصبح صحفياً؟",
        "من سيكون الأفضل في العناق؟",
        "من الأكثر احتمالاً أن يصبح مهندساً؟",
        "من الأكثر احتمالاً أن يتحدث مع نفسه؟",
        "من الأكثر احتمالاً أن يصبح ممرضاً؟",
        "من سيكون الأفضل في تكوين صداقات؟",
        "من الأكثر احتمالاً أن يصبح مدرباً؟",
        "من الأكثر احتمالاً أن يجمع شيئاً غريباً؟",
        "من الأكثر احتمالاً أن يصبح أمين مكتبة؟",
        "من سيكون الأفضل في حل النزاعات؟",
        "من الأكثر احتمالاً أن يصبح رجل إطفاء؟",
        "من الأكثر احتمالاً أن تكون غرفته الأكثر فوضى؟"
    ]
};

// Function to get random questions
function getRandomQuestions(language = 'en', count = 10) {
    const questions = questionsDatabase[language] || questionsDatabase.en;
    const shuffled = [...questions].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, count);
}

// Function to get a single random question
function getRandomQuestion(language = 'en') {
    const questions = questionsDatabase[language] || questionsDatabase.en;
    return questions[Math.floor(Math.random() * questions.length)];
}

// Export functions for use in other scripts
window.questionsDB = {
    getRandomQuestions,
    getRandomQuestion,
    getAllQuestions: (language = 'en') => questionsDatabase[language] || questionsDatabase.en
};